language: python
python:
 - '3.7.0'  # Test the .0 version for some breaking changes
 - '3.8'
install:
 - "pip install flake8 -e ."
script:
 - "flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics"
 - "python -m unittest discover -p '*_test.py' -v"
